### ISSUE TITLE
Sending Glitch

### ISSUE THREAD

**Issue by HeyItsMicro** [CreatureSurvive/bubbles#38] opened 2018-08-15 14:25 UTC
when I send a message, the whole screen goes blank except for the message and then once it’s sent it shows everything again

**Comment by CreatureSurvive** [comment] 2018-08-15 15:15
@notmicrodev I'm aware of the issue, and I'll be looking into it this evening

**Comment by CreatureSurvive** [comment] 2018-08-15 15:17
Duplicate of #36 I'm going to close this

**Closed as completed by CreatureSurvive** 2018-08-15 15:17 UTC
