### ISSUE TITLE
iMessage and SMS bubles coloring doesn't work when light theme is selected since last update

### ISSUE THREAD

**Issue by LOLXDXPLOL** [CreatureSurvive/bubbles#20] opened 2018-07-26 09:36 UTC
https://i.imgur.com/OeNnaH0.jpg

**Comment by CreatureSurvive** [comment] 2018-07-29 21:51
@LOLXDXPLOL I'm aware of the issue, hopefully, I'll have it fixed in today's update. I'm not able to reproduce the issue on my own device so its a bit tricky to test

**Comment by CreatureSurvive** [comment] 2018-08-02 03:07
@LOLXDXPLOL v0.2.2b is finally out, which fixes this issue. Sorry for the delay.

**Closed by CreatureSurvive** 2018-08-02 03:07 UTC
